:----------:|:---
`{`         | Move to beginning of previous paragraph
`}`         | Move to beginning of next paragraph
`$`         | Move to the end of the line
`?`         | Begin searching reverse, repeat last search in reverse
`/`         | Begin searching forward, repeat last search forward
`_`         | <s>Move to the beginning of the line</s>
`^`         | Move to the first non-blank character of current line
`0`         | Move to the beginning of the line
`a`         | Enter insert mode after the current point
`A`         | Enter insert mode at the end of the current line
`b,B`       | Move one word backward
`cw,c#w`    | Change word (or multiple)
`dd,d#d`    | Delete one or more lines, e.g., dd, d2d, d34d
`dh,d#h`    | Delete character from current location * left, e.g., dh, d2h, d34h
`dj,d#j`    | Delete character from current location * down, e.g., dj, d2j, d34j
`dk,d#k`    | Delete character from current location * up, e.g., dk, d2k, d34k
`dl,d#l`    | Delete character from current location * right, e.g., dl, d2l, d34l
`dw,d#w`    | Delete a word (or multiple)
`d$`        | Delete to end of line
`e,E`       | Move to end of word
`G,#G`      | Move to last line, or line number #
`h`         | Move left
`i`         | Enter insert mode
`I`         | Enter insert mode at the beginning of the current line
`j`         | Move down
`k`         | Move up
`l`         | Move right
`n`         | Repeat last search in the same direction
`N`         | Repeat last search in the opposite direction
`o`         | Enter insert mode on a new line
`O`         | Enter insert mode on a new line above
`p`         | <s>Puts back whatever is in the "kill" buffer (via Coca directly)</s>
`r\`*       | Replace the character under the cursor with typed character
`u`         | Undo last operation (this uses the Cocoa UndoManager directly)
`w,W`       | Move one word forward
`x`         | Delete character under the cursor

